schema_version: 1

context:
  version: "0.6.0"

package:
  name: pydantic-ai-harness
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pydantic-ai-harness/pydantic_ai_harness-${{ version }}.tar.gz
  sha256: 0e9bf052a0f4c21ec911e2dbf8e6b11c16aebee1455dd997ea6e079fb9fbc49a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - uv-dynamic-versioning >=0.7.0
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic-ai-slim >=1.95.1

tests:
  - python:
      imports:
        - pydantic_ai_harness
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: The batteries for your Pydantic AI agent
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pydantic/pydantic-ai-harness
  repository: https://github.com/pydantic/pydantic-ai-harness

extra:
  recipe-maintainers:
    - moritzwilksch
